root = "."
tmp_dir = "tmp"

[build]
  entrypoint = "./tmp/panya-charge-oss"
  cmd = "go build -o ./tmp/panya-charge-oss ./cmd/panya-charge-oss"
  delay = 1000
  exclude_regex = ["_test\\.go"]
  exclude_unchanged = true
  follow_symlink = false
  full_bin = "./tmp/panya-charge-oss"
  kill_delay = "5s"
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = true

[color]
  app = "cyan"
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true